-- Attendance: camera + GPS
ALTER TABLE attendance ADD COLUMN IF NOT EXISTS photo_url TEXT DEFAULT '';
ALTER TABLE attendance ADD COLUMN IF NOT EXISTS latitude DOUBLE PRECISION;
ALTER TABLE attendance ADD COLUMN IF NOT EXISTS longitude DOUBLE PRECISION;
ALTER TABLE attendance ADD COLUMN IF NOT EXISTS location_name TEXT DEFAULT '';
ALTER TABLE attendance ALTER COLUMN id TYPE TEXT;
ALTER TABLE attendance DROP CONSTRAINT IF EXISTS attendance_employee_id_fkey;
ALTER TABLE attendance ALTER COLUMN check_in TYPE TIMESTAMPTZ USING (date + check_in::TIME) AT TIME ZONE 'Asia/Jakarta';
ALTER TABLE attendance ALTER COLUMN check_out TYPE TIMESTAMPTZ USING (date + check_out::TIME) AT TIME ZONE 'Asia/Jakarta';

-- Employees: KK / Data Induk
ALTER TABLE employees ADD COLUMN IF NOT EXISTS nik TEXT DEFAULT '';
ALTER TABLE employees ADD COLUMN IF NOT EXISTS birth_place TEXT DEFAULT '';
ALTER TABLE employees ADD COLUMN IF NOT EXISTS birth_date DATE;
ALTER TABLE employees ADD COLUMN IF NOT EXISTS religion TEXT DEFAULT '';
ALTER TABLE employees ADD COLUMN IF NOT EXISTS blood_type TEXT DEFAULT '';
ALTER TABLE employees ADD COLUMN IF NOT EXISTS marital_status TEXT DEFAULT '';
ALTER TABLE employees ADD COLUMN IF NOT EXISTS spouse_name TEXT DEFAULT '';
ALTER TABLE employees ADD COLUMN IF NOT EXISTS children_count INTEGER DEFAULT 0;
ALTER TABLE employees ADD COLUMN IF NOT EXISTS ktp_address TEXT DEFAULT '';
ALTER TABLE employees ADD COLUMN IF NOT EXISTS last_education TEXT DEFAULT '';
ALTER TABLE employees ADD COLUMN IF NOT EXISTS emergency_name TEXT DEFAULT '';
ALTER TABLE employees ADD COLUMN IF NOT EXISTS emergency_phone TEXT DEFAULT '';
