-- Attendance: camera + GPS
ALTER TABLE attendance ADD COLUMN IF NOT EXISTS photo_url TEXT DEFAULT '';
ALTER TABLE attendance ADD COLUMN IF NOT EXISTS latitude DOUBLE PRECISION;
ALTER TABLE attendance ADD COLUMN IF NOT EXISTS longitude DOUBLE PRECISION;
ALTER TABLE attendance ADD COLUMN IF NOT EXISTS location_name TEXT DEFAULT '';

-- Employees: KK / Data Induk
ALTER TABLE employees ADD COLUMN IF NOT EXISTS nik TEXT DEFAULT '';
ALTER TABLE employees ADD COLUMN IF NOT EXISTS birth_place TEXT DEFAULT '';
ALTER TABLE employees ADD COLUMN IF NOT EXISTS birth_date DATE;
ALTER TABLE employees ADD COLUMN IF NOT EXISTS religion TEXT DEFAULT '';
ALTER TABLE employees ADD COLUMN IF NOT EXISTS blood_type TEXT DEFAULT '';
ALTER TABLE employees ADD COLUMN IF NOT EXISTS marital_status TEXT DEFAULT '';
ALTER TABLE employees ADD COLUMN IF NOT EXISTS spouse_name TEXT DEFAULT '';
ALTER TABLE employees ADD COLUMN IF NOT EXISTS children_count INTEGER DEFAULT 0;
ALTER TABLE employees ADD COLUMN IF NOT EXISTS ktp_address TEXT DEFAULT '';
ALTER TABLE employees ADD COLUMN IF NOT EXISTS last_education TEXT DEFAULT '';
ALTER TABLE employees ADD COLUMN IF NOT EXISTS emergency_name TEXT DEFAULT '';
ALTER TABLE employees ADD COLUMN IF NOT EXISTS emergency_phone TEXT DEFAULT '';
